# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b7a5dcae55491906f3e39be79553dca9bc19a1c5aafc9726d4a2c743475ba07b21818a61da2836792e2c88af310a8fb9821268803296463917d1d2c6bb3cd2

test:
  secret_key_base: 2218445e99bae1b47c4aa062fe170b67fead243f86007d92698471519e397c8ad2dda7c426208ae499ef925ed84d421e3cd903a41d38bf5610bd7c74be9efdf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
